export const DEMO_GUEST_USER = {
  id: 'guest-user-101',
  email: 'guest@classspace.edu',
}

export const DEMO_GUEST_PROFILE = {
  id: 'guest-user-101',
  classroom_id: 'class-demo-101',
  email: 'guest@classspace.edu',
  full_name: 'Alex Rivera (Guest)',
  nickname: 'Alex',
  username: 'alex_rivera',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  role: 'admin',
  status: 'approved',
  points: 1450,
  tier: 'Class A • Elite',
  student_id_code: 'ANHS-0101',
  bio: 'Computer Science enthusiast exploring ClassSpace! Passionate about web development, AI, and building community platforms.',
  favorite_subjects: ['Web Systems', 'Algorithms', 'UI/UX Design', 'Database Architecture'],
  skills: ['Next.js', 'TypeScript', 'Tailwind CSS', 'PostgreSQL', 'Python'],
  hobbies: ['Hackathons', 'Photography', 'Chess', 'Indie Game Dev'],
  achievements: ['Dean\'s List 2025', '1st Place Web Hackathon', 'S-Rank Merit Contributor'],
  github_url: 'https://github.com',
  linkedin_url: 'https://linkedin.com',
  portfolio_url: 'https://example.com',
  show_birthday: true,
  birthday: '2005-08-15',
  profile_accent: 'indigo',
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
}

export const DEMO_CLASSMATES = [
  DEMO_GUEST_PROFILE,
  {
    id: 'demo-student-2',
    classroom_id: 'class-demo-101',
    email: 'maya.lin@classspace.edu',
    full_name: 'Maya Lin',
    nickname: 'Maya',
    username: 'mayalin',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    role: 'student',
    status: 'approved',
    points: 1820,
    tier: 'Class A • Representative',
    student_id_code: 'ANHS-0102',
    bio: 'UI/UX Designer & Frontend Developer. Building interfaces that delight people.',
    favorite_subjects: ['Interactive Design', 'Human-Computer Interaction', 'Typography'],
    skills: ['Figma', 'React', 'Tailwind CSS', 'CSS Animations'],
    hobbies: ['Digital Art', 'Coffee Brewing', 'Bouldering'],
    achievements: ['Design Lead at Creative Tech Club', 'Top Merit Score Q1'],
    github_url: 'https://github.com',
    linkedin_url: 'https://linkedin.com',
    portfolio_url: 'https://example.com',
    show_birthday: true,
    birthday: '2004-11-20',
    profile_accent: 'emerald',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'demo-student-3',
    classroom_id: 'class-demo-101',
    email: 'jordan.taylor@classspace.edu',
    full_name: 'Jordan Taylor',
    nickname: 'JT',
    username: 'jtaylor_dev',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    role: 'student',
    status: 'approved',
    points: 1210,
    tier: 'Class B • Advanced',
    student_id_code: 'ANHS-0103',
    bio: 'Backend & Cloud Infrastructure geek. Obsessed with high-performance Rust and distributed systems.',
    favorite_subjects: ['Operating Systems', 'Cloud Computing', 'Computer Networks'],
    skills: ['Rust', 'Go', 'Docker', 'Kubernetes', 'PostgreSQL'],
    hobbies: ['HomeLab Server Building', 'Mechanical Keyboards', 'Sci-Fi Reading'],
    achievements: ['AWS Certified Cloud Practitioner'],
    github_url: 'https://github.com',
    linkedin_url: 'https://linkedin.com',
    portfolio_url: '',
    show_birthday: true,
    birthday: '2004-04-12',
    profile_accent: 'blue',
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'demo-student-4',
    classroom_id: 'class-demo-101',
    email: 'sofia.chen@classspace.edu',
    full_name: 'Sofia Chen',
    nickname: 'Sofi',
    username: 'sofi_data',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    role: 'student',
    status: 'approved',
    points: 1640,
    tier: 'Class A • Elite',
    student_id_code: 'ANHS-0104',
    bio: 'Data Science & Machine Learning researcher. Working on NLP and educational analytics.',
    favorite_subjects: ['Machine Learning', 'Linear Algebra', 'Data Visualization'],
    skills: ['Python', 'PyTorch', 'Pandas', 'SQL', 'Next.js'],
    hobbies: ['Violin', 'Tennis', 'Hackathons'],
    achievements: ['Published Undergraduate AI Paper', 'Merit Honor Roll'],
    github_url: 'https://github.com',
    linkedin_url: 'https://linkedin.com',
    portfolio_url: 'https://example.com',
    show_birthday: true,
    birthday: '2005-02-28',
    profile_accent: 'purple',
    created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'demo-student-5',
    classroom_id: 'class-demo-101',
    email: 'liam.patel@classspace.edu',
    full_name: 'Liam Patel',
    nickname: 'Liam',
    username: 'liampatel',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    role: 'student',
    status: 'approved',
    points: 950,
    tier: 'Class B • Regular',
    student_id_code: 'ANHS-0105',
    bio: 'Mobile App Developer & Indie Creator. Creator of StudyNotes mobile app with 5K+ downloads.',
    favorite_subjects: ['Mobile Development', 'Software Architecture', 'Entrepreneurship'],
    skills: ['React Native', 'Swift', 'TypeScript', 'Firebase', 'Supabase'],
    hobbies: ['Running', 'Podcasting', 'Guitar'],
    achievements: ['Campus Startup Pitch Winner'],
    github_url: 'https://github.com',
    linkedin_url: 'https://linkedin.com',
    portfolio_url: 'https://example.com',
    show_birthday: true,
    birthday: '2004-09-05',
    profile_accent: 'amber',
    created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'demo-student-6',
    classroom_id: 'class-demo-101',
    email: 'elena.rostova@classspace.edu',
    full_name: 'Elena Rostova',
    nickname: 'Elena',
    username: 'elena_sec',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    role: 'student',
    status: 'approved',
    points: 1100,
    tier: 'Class B • Advanced',
    student_id_code: 'ANHS-0106',
    bio: 'Cybersecurity & Ethical Hacking student. Interested in cryptography and web security.',
    favorite_subjects: ['Cybersecurity', 'Network Defense', 'Cryptography'],
    skills: ['Linux', 'Network Security', 'Python', 'C++'],
    hobbies: ['CTF Competitions', 'Rock Climbing', 'Mystery Novels'],
    achievements: ['Top 10 National CTF Qualifier'],
    github_url: 'https://github.com',
    linkedin_url: 'https://linkedin.com',
    portfolio_url: '',
    show_birthday: true,
    birthday: '2005-01-14',
    profile_accent: 'rose',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  }
]

export const DEMO_PROJECTS = [
  {
    id: 'demo-project-1',
    profile_id: 'guest-user-101',
    title: 'ClassSpace Classroom Portal',
    description: 'A comprehensive private classroom directory and student portfolio platform built with Next.js 16, TypeScript, Tailwind CSS, and Supabase.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Supabase', 'Zod'],
    repo_url: 'https://github.com/example/classspace',
    live_url: 'http://localhost:3000',
    project_date: '2026-07-01',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-project-2',
    profile_id: 'guest-user-101',
    title: 'AI Study Notes Generator',
    description: 'An intelligent study assistant that automatically creates flashcards and summary outlines from classroom lecture PDFs.',
    technologies: ['Python', 'FastAPI', 'React', 'OpenAI API'],
    repo_url: 'https://github.com/example/ai-study-notes',
    live_url: 'https://example.com',
    project_date: '2026-05-15',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-project-3',
    profile_id: 'demo-student-2',
    title: 'Campus Interactive Transit Map',
    description: 'A real-time shuttle bus tracker and campus accessibility guide designed for university students and visitors.',
    technologies: ['React', 'Mapbox GL', 'Node.js', 'WebSockets'],
    repo_url: 'https://github.com/example/campus-transit',
    live_url: 'https://example.com',
    project_date: '2026-04-10',
    is_public: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const DEMO_ANNOUNCEMENTS = [
  {
    id: 'demo-announce-1',
    classroom_id: 'class-demo-101',
    author_id: 'guest-user-101',
    title: '🎉 Welcome to ClassSpace! Explore Demo Mode',
    content: 'Welcome to our private digital yearbook! You can browse classmate portfolios in the Directory, discover projects in the Showcase, and customize your profile.',
    is_pinned: true,
    expires_at: new Date(Date.now() + 86400000 * 30).toISOString(),
    created_at: new Date().toISOString(),
    author: {
      full_name: 'Alex Rivera (Guest)',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    }
  },
  {
    id: 'demo-announce-2',
    classroom_id: 'class-demo-101',
    author_id: 'guest-user-101',
    title: '📅 Midterm Project Showcase Presentation Night',
    content: 'Don’t forget to upload your latest semester project to your ClassSpace portfolio before Friday at 5:00 PM!',
    is_pinned: false,
    expires_at: new Date(Date.now() + 86400000 * 14).toISOString(),
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    author: {
      full_name: 'Alex Rivera (Guest)',
      avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    }
  }
]
